export const PATHS = {
  admins: '/admins',
  adminCreate: '/admins/create',
  adminUpdate: '/admins/update',
  changePassword: '/changePassword',
  dashboard: '/dashboard',
  notifications: '/notifications',
  users: '/users',
  user: '/user/view',
  userUpdate: '/user/update',
  resetPassword: '/reset-password',
  root: '',
  settings: '/settings',
  signUp: '/sign-up',
  signIn: '/sign-in',
  tags: '/tags',
  tagCreate: '/tags/create',
  translationDetails: '/translation',
  translations: '/translations',
};
