nodeLinker: node-modules

npmScopes:
  apptractive:
    npmAlwaysAuth: true
    npmAuthToken: "${NODE_AUTH_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.1.1.cjs
